# Python Libraries for Data Science
- Numpy
- Pandas
- Matplotlib

# Numpy
- Numerical python is base N-dimensional array package.
- It is python library
- it is used to create multidimensional arrays for fast operations.


In [2]:
# create 1D
import numpy as np
ar_1d = np.array([2,3,6,8,9,4])
print(ar_1d)

[2 3 6 8 9 4]


In [4]:
# create 2D
import numpy as np
ar_2d = np.array([[2,3,6],[8,9,4]])
print(ar_2d)

[[2 3 6]
 [8 9 4]]


In [5]:
# create 3D
import numpy as np
ar_3d = np.array([[2,3,6],[8,9,4],[5,10,1]])
print(ar_3d)

[[ 2  3  6]
 [ 8  9  4]
 [ 5 10  1]]


In [9]:
# create array
import numpy as np
x = [2,3,6,7,8]
a = np.array(x)
print(a)

[2 3 6 7 8]


In [16]:
import numpy as np
x = np.arange(10)
print(x)

[0 1 2 3 4 5 6 7 8 9]


In [21]:
import numpy as np
x = np.arange(10).reshape(2,5)
print(x)

[[0 1 2 3 4]
 [5 6 7 8 9]]


In [23]:
# reversing array
x[::-1]

array([[5, 6, 7, 8, 9],
       [0, 1, 2, 3, 4]])

In [24]:
z = np.array([1,2])
z

array([1, 2])

In [25]:
z[::-1]

array([2, 1])

In [27]:
import numpy as np
a = np.ones((3,3))
print(a)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [31]:
import numpy as np
a = np.zeros((4,3))
print(a)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [32]:
x

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [33]:
y = x + 1
y

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [34]:
z = y + 3
z

array([[ 4,  5,  6,  7,  8],
       [ 9, 10, 11, 12, 13]])

In [37]:
a = [1,2,3]
x = np.array(a)
print(np.sqrt(x))

[1.         1.41421356 1.73205081]


In [38]:
print(np.sin(x))

[0.84147098 0.90929743 0.14112001]


In [39]:
print(np.cos(x))

[ 0.54030231 -0.41614684 -0.9899925 ]


In [40]:
print(np.log(x))

[0.         0.69314718 1.09861229]


# pandas
- it is derived from "PANel Data"
- there are 2 main data structures in pandas
  - Series
  - Dataframes

In [41]:
import pandas as pd
s = pd.Series([1,3,5])
print(s)

0    1
1    3
2    5
dtype: int64


In [42]:
import pandas as pd
s1 = pd.Series(['s','a','n','a'])
print(s1)

0    s
1    a
2    n
3    a
dtype: object


In [44]:
s1[2]

'n'

In [45]:
s1[2:]

2    n
3    a
dtype: object

In [46]:
pd.Series([0,1,2,3], index=['a','b','c','d'])

a    0
b    1
c    2
d    3
dtype: int64

In [48]:
pd.Series([20,21,22,23,24], index=pd.date_range('20-8-2020','24-8-2020'))

2020-08-20    20
2020-08-21    21
2020-08-22    22
2020-08-23    23
2020-08-24    24
Freq: D, dtype: int64

In [50]:
pd.Series(range(5), index=pd.date_range('20-8-2020','24-8-2020'))

2020-08-20    0
2020-08-21    1
2020-08-22    2
2020-08-23    3
2020-08-24    4
Freq: D, dtype: int64

In [51]:
import pandas as pd
import numpy as np
pd.Series(np.array(range(0,10))**2, index=range(0,10))

0     0
1     1
2     4
3     9
4    16
5    25
6    36
7    49
8    64
9    81
dtype: int32

In [53]:
#DataFrames
import pandas as pd
data = [['a',10],['b',20],['c',30]]
df = pd.DataFrame(data,columns=["string","int"])
df

string  int
0      a   10
1      b   20
2      c   30

In [60]:
import pandas as pd
d1 = {'s1':10,'s2':20,'s3':30}
d1 = pd.Series(d1)
d1

s1    10
s2    20
s3    30
dtype: int64

In [61]:
import pandas as pd
d2 = {'s1':15,'s2':25,'s3':35}
d2 = pd.Series(d2)
d2

s1    15
s2    25
s3    35
dtype: int64

In [63]:
names = {"sana":d1,"sudha":d2}
names = pd.DataFrame(names)
names

sana  sudha
s1    10     15
s2    20     25
s3    30     35

In [65]:
import pandas as pd
df = pd.DataFrame({'namae':['sana','sudha'],'age':[25,26],"quali":['btech','mtech']})
df

namae  age  quali
0   sana   25  btech
1  sudha   26  mtech

In [ ]:
https://pandas.pydata.org/

In [70]:
# iterators
s = iter('python')
print(next(s))
print(next(s))
print(next(s))
print(next(s))
print(next(s))
print(next(s))

p
y
t
h
o
n


In [72]:
names=['sana','sudha','siva']
result=iter(names)
print(next(result))
print(next(result))
print(next(result))

sana
sudha
siva


In [73]:
# generators
def gen():
    n=2
    while True:
        n**=2 #2^2=4,4^2=16,16^2=256....
        yield n
a=gen()
for i in range(5):
    print(next(a))

4
16
256
65536
4294967296
