### NumPy
- Numpy is a base N-dimensional array and used as a fundamental package for scientific computing
- import numpy as np

In [1]:
import numpy as np

In [6]:
! pip install numpy

In [5]:
k = [1,2,3,4]
a = np.array(k)
print(a)
a

[1 2 3 4]


array([1, 2, 3, 4])

In [10]:
a1 = np.array([1,7,8,9,78])
a1.size

5

In [9]:
np.arange(1,15)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [20]:
n= np.random.randint(0,67,15)
n.shape

(15,)

In [19]:
n1 = np.random.randint(0,2,size = (3,3,3))
print("ndim",n1.ndim)
print(n1.shape)
print(n1.size)
print("itemsize",n1.itemsize)
print(n1.dtype)

ndim 3
(3, 3, 3)
27
itemsize 4
int32


### NumPy properties
- ndim
    - returns the no of dimensions
- shape
    - returns the length of an array in tuple format
- size 
    - it returns the count of elements
- itemsize
    - returns the size of an element in bytes
- dtype
    - returns the datatype of an element

In [22]:
n= np.random.randint(0,67,15).reshape(3,5)
n

array([[22, 54, 43, 18, 52],
       [27, 44, 42, 30, 39],
       [38, 66, 48, 22, 39]])

In [23]:
n[::-1]

array([[38, 66, 48, 22, 39],
       [27, 44, 42, 30, 39],
       [22, 54, 43, 18, 52]])

In [24]:
np.linspace(0,3,4) # creates an array of evenly spaced values

array([0., 1., 2., 3.])

In [25]:
np.linspace(0,2,7)

array([0.        , 0.33333333, 0.66666667, 1.        , 1.33333333,
       1.66666667, 2.        ])

In [28]:
one = np.ones((2,3,5))

In [29]:
one

array([[[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]]])

In [30]:
z = np.zeros((2,2))
z

array([[0., 0.],
       [0., 0.]])

In [35]:
np.info(np.linspace)

 linspace(start, stop, num=50, endpoint=True, retstep=False, dtype=None)

Return evenly spaced numbers over a specified interval.

Returns `num` evenly spaced samples, calculated over the
interval [`start`, `stop`].

The endpoint of the interval can optionally be excluded.

Parameters
----------
start : scalar
    The starting value of the sequence.
stop : scalar
    The end value of the sequence, unless `endpoint` is set to False.
    In that case, the sequence consists of all but the last of ``num + 1``
    evenly spaced samples, so that `stop` is excluded.  Note that the step
    size changes when `endpoint` is False.
num : int, optional
    Number of samples to generate. Default is 50. Must be non-negative.
endpoint : bool, optional
    If True, `stop` is the last sample. Otherwise, it is not included.
    Default is True.
retstep : bool, optional
    If True, return (`samples`, `step`), where `step` is the spacing
    between samples.
dtype : dtype, optional
    The type of the ou

In [50]:
f = np.full((2,3),5) # creates an array of constant element
f.dtype
f.astype(str)

array([['5', '5', '5'],
       ['5', '5', '5']], dtype='<U11')

In [37]:
e = np.eye(3) # creates a 3 x 3 identity matrix
e

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [47]:
em =np.empty((2,3))
em

array([[1., 1., 1.],
       [1., 1., 1.]])

In [45]:
r = np.random.random((2,2))
r

array([[0.65984025, 0.10876163],
       [0.06076808, 0.52274222]])

In [53]:
a = np.array([1,2,3,4,5])
b = np.array([1,5,7,8,3])
print(a+b)
print(a-b)

[ 2  7 10 12  8]
[ 0 -3 -4 -4  2]


In [60]:
print(np.add(a,b)) # subtract,multiply,divide

[ 2  7 10 12  8]


In [62]:
np.mod(a,b)

array([0, 2, 3, 4, 2], dtype=int32)

In [64]:
np.power(a,b)

array([    1,    32,  2187, 65536,   125], dtype=int32)

In [65]:
a

array([1, 2, 3, 4, 5])

In [66]:
print(np.exp(a))
print(np.log(a))

[  2.71828183   7.3890561   20.08553692  54.59815003 148.4131591 ]
[0.         0.69314718 1.09861229 1.38629436 1.60943791]


In [67]:
np.sin(a)
np.cos(a)
np.sqrt(a)

array([1.        , 1.41421356, 1.73205081, 2.        , 2.23606798])

In [68]:
a.dot(b)

79

In [70]:
print(np.sum(a))
print(a.min())
print(a.max())

15
1
5


In [71]:
print(np.cumsum(a))

[ 1  3  6 10 15]


In [74]:
print(a.mean())
print(np.median(a))
print(a.std())
print(np.corrcoef(a))

3.0
3.0
1.4142135623730951
1.0


In [76]:
print(a<3)

[ True  True False False False]


In [77]:
print(a==b)

[ True False False False False]


In [78]:
np.array_equal(a,b)

False

In [2]:
a = np.array([1,34,2,7,8,25,98,67])
a

array([ 1, 34,  2,  7,  8, 25, 98, 67])

In [3]:
a.sort()

In [4]:
a

array([ 1,  2,  7,  8, 25, 34, 67, 98])

In [7]:
a.sort()
a

array([ 1,  2,  7,  8, 25, 34, 67, 98])

In [8]:
b = np.array([[23,56,8],[1,34,89]])
b.sort(axis=0)
b

array([[ 1, 34,  8],
       [23, 56, 89]])

In [9]:
b.sort(axis=1)
b

array([[ 1,  8, 34],
       [23, 56, 89]])

In [12]:
b[0][1]

8

In [15]:
b[1,2] # b[1][2]

89

In [20]:
b[0:2,1]

array([ 8, 56])

In [23]:
b[0,:2]

array([1, 8])

In [24]:
b[1,:]

array([23, 56, 89])

In [25]:
b

array([[ 1,  8, 34],
       [23, 56, 89]])

In [29]:
b[[0,0],[1,1]] # b[0,1][1,1]

array([8, 8])

In [30]:
b

array([[ 1,  8, 34],
       [23, 56, 89]])

In [31]:
b.T

array([[ 1, 23],
       [ 8, 56],
       [34, 89]])

In [33]:
b

array([[ 1,  8, 34],
       [23, 56, 89]])

In [32]:
b.transpose()

array([[ 1, 23],
       [ 8, 56],
       [34, 89]])

In [34]:
b.flatten()

array([ 1,  8, 34, 23, 56, 89])

In [36]:
np.r_[b]

array([[ 1,  8, 34],
       [23, 56, 89]])

In [37]:
np.c_[b]

array([[ 1,  8, 34],
       [23, 56, 89]])

In [53]:
a = np.full((2,2),7)
b = np.arange(0,4).reshape(2,-2)
b

array([[0, 1],
       [2, 3]])

In [44]:
np.c_[a,b] # stacks the array horizontally (column-wise)

array([[7, 7, 0, 1],
       [7, 7, 2, 3]])

In [45]:
np.r_[a,b] # stacks the array vertically (row-wise)

array([[7, 7],
       [7, 7],
       [0, 1],
       [2, 3]])

In [46]:
np.hstack((a,b)) # stacks the array horizontally (column-wise) (c_)

array([[7, 7, 0, 1],
       [7, 7, 2, 3]])

In [47]:
np.vstack((a,b)) # stacks the array vertically (row-wise) (r_)

array([[7, 7],
       [7, 7],
       [0, 1],
       [2, 3]])

In [55]:
np.column_stack((a,b)) # hstack(),c_
np.row_stack((a,b)) # vstack(),r_

array([[7, 7],
       [7, 7],
       [0, 1],
       [2, 3]])

In [60]:
b.ravel()

array([0, 1, 2, 3])

In [61]:
np.insert(b,1,5)

array([0, 5, 1, 2, 3])

In [70]:
n = np.delete(b,2)
n

array([0, 1, 3])

In [68]:
b

array([[0, 1],
       [2, 3]])

In [65]:
a = np.array([])
a

array([], dtype=float64)

In [72]:
print(np.hsplit(b,2))

[array([[0],
       [2]]), array([[1],
       [3]])]


In [73]:
print(np.vsplit(b,2))

[array([[0, 1]]), array([[2, 3]])]


In [77]:
n = np.array([[1,2],[4,5],[9,6]])
n

array([[1, 2],
       [4, 5],
       [9, 6]])

In [78]:
np.vsplit(n,3)

[array([[1, 2]]), array([[4, 5]]), array([[9, 6]])]

In [81]:
np.hsplit(n,2)

[array([[1],
        [4],
        [9]]), array([[2],
        [5],
        [6]])]